export const COUNTRIES = 
[
  { alpha2_code: "AF", countryName: "Afghanistan" },
  { alpha2_code: "AX", countryName: "Aland Islands" },
  { alpha2_code: "AL", countryName: "Albania" },
  { alpha2_code: "DZ", countryName: "Algeria" },
  { alpha2_code: "AS", countryName: "American Samoa" },
  { alpha2_code: "AD", countryName: "Andorra" },
  { alpha2_code: "AO", countryName: "Angola" },
  { alpha2_code: "AI", countryName: "Anguilla" },
  { alpha2_code: "AQ", countryName: "Antarctica" },
  { alpha2_code: "AG", countryName: "Antigua and Barbuda" },
  { alpha2_code: "AR", countryName: "Argentina" },
  { alpha2_code: "AM", countryName: "Armenia" },
  { alpha2_code: "AW", countryName: "Aruba" },
  { alpha2_code: "AU", countryName: "Australia" },
  { alpha2_code: "AT", countryName: "Austria" },
  { alpha2_code: "AZ", countryName: "Azerbaijan" },
  { alpha2_code: "BS", countryName: "Bahamas" },
  { alpha2_code: "BH", countryName: "Bahrain" },
  { alpha2_code: "BD", countryName: "Bangladesh" },
  { alpha2_code: "BB", countryName: "Barbados" },
  { alpha2_code: "BY", countryName: "Belarus" },
  { alpha2_code: "BE", countryName: "Belgium" },
  { alpha2_code: "BZ", countryName: "Belize" },
  { alpha2_code: "BJ", countryName: "Benin" },
  { alpha2_code: "BM", countryName: "Bermuda" },
  { alpha2_code: "BT", countryName: "Bhutan" },
  { alpha2_code: "BO", countryName: "Bolivia" },
  { alpha2_code: "BQ", countryName: "Bonaire, Sint Eustatius and Saba" },
  { alpha2_code: "BA", countryName: "Bosnia and Herzegovina" },
  { alpha2_code: "BW", countryName: "Botswana" },
  { alpha2_code: "BV", countryName: "Bouvet Island" },
  { alpha2_code: "BR", countryName: "Brazil" },
  { alpha2_code: "IO", countryName: "British Indian Ocean Territory" },
  { alpha2_code: "BN", countryName: "Brunei Darussalam" },
  { alpha2_code: "BG", countryName: "Bulgaria" },
  { alpha2_code: "BF", countryName: "Burkina Faso" },
  { alpha2_code: "BI", countryName: "Burundi" },
  { alpha2_code: "KH", countryName: "Cambodia" },
  { alpha2_code: "CM", countryName: "Cameroon" },
  { alpha2_code: "CA", countryName: "Canada" },
  { alpha2_code: "CV", countryName: "Cape Verde" },
  { alpha2_code: "KY", countryName: "Cayman Islands" },
  { alpha2_code: "CF", countryName: "Central African Republic" },
  { alpha2_code: "TD", countryName: "Chad" },
  { alpha2_code: "CL", countryName: "Chile" },
  { alpha2_code: "CN", countryName: "China" },
  { alpha2_code: "CX", countryName: "Christmas Island" },
  { alpha2_code: "CC", countryName: "Cocos (Keeling) Islands" },
  { alpha2_code: "CO", countryName: "Colombia" },
  { alpha2_code: "KM", countryName: "Comoros" },
  { alpha2_code: "CG", countryName: "Congo" },
  { alpha2_code: "CD", countryName: "Congo, The Democratic Republic of " },
  { alpha2_code: "CK", countryName: "Cook Islands" },
  { alpha2_code: "CR", countryName: "Costa Rica" },
  { alpha2_code: "CI", countryName: "Cote d'Ivoire" },
  { alpha2_code: "HR", countryName: "Croatia" },
  { alpha2_code: "CU", countryName: "Cuba" },
  { alpha2_code: "CW", countryName: "Curaçao" },
  { alpha2_code: "CY", countryName: "Cyprus" },
  { alpha2_code: "CZ", countryName: "Czechia" },
  { alpha2_code: "DK", countryName: "Denmark" },
  { alpha2_code: "DJ", countryName: "Djibouti" },
  { alpha2_code: "DM", countryName: "Dominica" },
  { alpha2_code: "DO", countryName: "Dominican Republic" },
  { alpha2_code: "EC", countryName: "Ecuador" },
  { alpha2_code: "EG", countryName: "Egypt" },
  { alpha2_code: "SV", countryName: "El Salvador" },
  { alpha2_code: "GQ", countryName: "Equatorial Guinea" },
  { alpha2_code: "ER", countryName: "Eritrea" },
  { alpha2_code: "EE", countryName: "Estonia" },
  { alpha2_code: "ET", countryName: "Ethiopia" },
  { alpha2_code: "FK", countryName: "Falkland Islands (Malvinas)" },
  { alpha2_code: "FO", countryName: "Faroe Islands" },
  { alpha2_code: "FJ", countryName: "Fiji" },
  { alpha2_code: "FI", countryName: "Finland" },
  { alpha2_code: "FR", countryName: "France" },
  { alpha2_code: "GF", countryName: "French Guiana" },
  { alpha2_code: "PF", countryName: "French Polynesia" },
  { alpha2_code: "TF", countryName: "French Southern Territories" },
  { alpha2_code: "GA", countryName: "Gabon" },
  { alpha2_code: "GM", countryName: "Gambia" },
  { alpha2_code: "GE", countryName: "Georgia" },
  { alpha2_code: "DE", countryName: "Germany" },
  { alpha2_code: "GH", countryName: "Ghana" },
  { alpha2_code: "GI", countryName: "Gibraltar" },
  { alpha2_code: "GR", countryName: "Greece" },
  { alpha2_code: "GL", countryName: "Greenland" },
  { alpha2_code: "GD", countryName: "Grenada" },
  { alpha2_code: "GP", countryName: "Guadeloupe" },
  { alpha2_code: "GU", countryName: "Guam" },
  { alpha2_code: "GT", countryName: "Guatemala" },
  { alpha2_code: "GG", countryName: "Guernsey" },
  { alpha2_code: "GN", countryName: "Guinea" },
  { alpha2_code: "GW", countryName: "Guinea-Bissau" },
  { alpha2_code: "GY", countryName: "Guyana" },
  { alpha2_code: "HT", countryName: "Haiti" },
  { alpha2_code: "HM", countryName: "Heard and Mc Donald Islands" },
  { alpha2_code: "VA", countryName: "Holy See (Vatican City State)" },
  { alpha2_code: "HN", countryName: "Honduras" },
  { alpha2_code: "HK", countryName: "Hong Kong" },
  { alpha2_code: "HU", countryName: "Hungary" },
  { alpha2_code: "IS", countryName: "Iceland" },
  { alpha2_code: "IN", countryName: "India" },
  { alpha2_code: "ID", countryName: "Indonesia" },
  { alpha2_code: "IR", countryName: "Iran, Islamic Republic of" },
  { alpha2_code: "IQ", countryName: "Iraq" },
  { alpha2_code: "IE", countryName: "Ireland" },
  { alpha2_code: "IM", countryName: "Isle of Man" },
  { alpha2_code: "IL", countryName: "Israel" },
  { alpha2_code: "IT", countryName: "Italy" },
  { alpha2_code: "JM", countryName: "Jamaica" },
  { alpha2_code: "JP", countryName: "Japan" },
  { alpha2_code: "JE", countryName: "Jersey" },
  { alpha2_code: "JO", countryName: "Jordan" },
  { alpha2_code: "KZ", countryName: "Kazakstan" },
  { alpha2_code: "KE", countryName: "Kenya" },
  { alpha2_code: "KI", countryName: "Kiribati" },
  { alpha2_code: "KP", countryName: "Korea, Democratic People's Republic of" },
  { alpha2_code: "KR", countryName: "Korea, Republic of" },
  { alpha2_code: "XK", countryName: "Kosovo (temporary code)" },
  { alpha2_code: "KW", countryName: "Kuwait" },
  { alpha2_code: "KG", countryName: "Kyrgyzstan" },
  { alpha2_code: "LA", countryName: "Lao, People's Democratic Republic" },
  { alpha2_code: "LV", countryName: "Latvia" },
  { alpha2_code: "LB", countryName: "Lebanon" },
  { alpha2_code: "LS", countryName: "Lesotho" },
  { alpha2_code: "LR", countryName: "Liberia" },
  { alpha2_code: "LY", countryName: "Libyan Arab Jamahiriya" },
  { alpha2_code: "LI", countryName: "Liechtenstein" },
  { alpha2_code: "LT", countryName: "Lithuania" },
  { alpha2_code: "LU", countryName: "Luxembourg" },
  { alpha2_code: "MO", countryName: "Macao" },
  { alpha2_code: "MK", countryName: "Macedonia, The Former Yugoslav Republic Of" },
  { alpha2_code: "MG", countryName: "Madagascar" },
  { alpha2_code: "MW", countryName: "Malawi" },
  { alpha2_code: "MY", countryName: "Malaysia" },
  { alpha2_code: "MV", countryName: "Maldives" },
  { alpha2_code: "ML", countryName: "Mali" },
  { alpha2_code: "MT", countryName: "Malta" },
  { alpha2_code: "MH", countryName: "Marshall Islands" },
  { alpha2_code: "MQ", countryName: "Martinique" },
  { alpha2_code: "MR", countryName: "Mauritania" },
  { alpha2_code: "MU", countryName: "Mauritius" },
  { alpha2_code: "YT", countryName: "Mayotte" },
  { alpha2_code: "MX", countryName: "Mexico" },
  { alpha2_code: "FM", countryName: "Micronesia, Federated States of" },
  { alpha2_code: "MD", countryName: "Moldova, Republic of" },
  { alpha2_code: "MC", countryName: "Monaco" },
  { alpha2_code: "MN", countryName: "Mongolia" },
  { alpha2_code: "ME", countryName: "Montenegro" },
  { alpha2_code: "MS", countryName: "Montserrat" },
  { alpha2_code: "MA", countryName: "Morocco" },
  { alpha2_code: "MZ", countryName: "Mozambique" },
  { alpha2_code: "MM", countryName: "Myanmar" },
  { alpha2_code: "NA", countryName: "Namibia" },
  { alpha2_code: "NR", countryName: "Nauru" },
  { alpha2_code: "NP", countryName: "Nepal" },
  { alpha2_code: "NL", countryName: "Netherlands" },
  { alpha2_code: "AN", countryName: "Netherlands Antilles" },
  { alpha2_code: "NC", countryName: "New Caledonia" },
  { alpha2_code: "NZ", countryName: "New Zealand" },
  { alpha2_code: "NI", countryName: "Nicaragua" },
  { alpha2_code: "NE", countryName: "Niger" },
  { alpha2_code: "NG", countryName: "Nigeria" },
  { alpha2_code: "NU", countryName: "Niue" },
  { alpha2_code: "NF", countryName: "Norfolk Island" },
  { alpha2_code: "MP", countryName: "Northern Mariana Islands" },
  { alpha2_code: "NO", countryName: "Norway" },
  { alpha2_code: "OM", countryName: "Oman" },
  { alpha2_code: "PK", countryName: "Pakistan" },
  { alpha2_code: "PW", countryName: "Palau" },
  { alpha2_code: "PS", countryName: "Palestinian Territory, Occupied" },
  { alpha2_code: "PA", countryName: "Panama" },
  { alpha2_code: "PG", countryName: "Papua New Guinea" },
  { alpha2_code: "PY", countryName: "Paraguay" },
  { alpha2_code: "PE", countryName: "Peru" },
  { alpha2_code: "PH", countryName: "Philippines" },
  { alpha2_code: "PN", countryName: "Pitcairn" },
  { alpha2_code: "PL", countryName: "Poland" },
  { alpha2_code: "PT", countryName: "Portugal" },
  { alpha2_code: "PR", countryName: "Puerto Rico" },
  { alpha2_code: "QA", countryName: "Qatar" },
  { alpha2_code: "RS", countryName: "Republic of Serbia" },
  { alpha2_code: "RE", countryName: "Reunion" },
  { alpha2_code: "RO", countryName: "Romania" },
  { alpha2_code: "RU", countryName: "Russia Federation" },
  { alpha2_code: "RW", countryName: "Rwanda" },
  { alpha2_code: "BL", countryName: "Saint Barthélemy" },
  { alpha2_code: "SH", countryName: "Saint Helena" },
  { alpha2_code: "KN", countryName: "Saint Kitts & Nevis" },
  { alpha2_code: "LC", countryName: "Saint Lucia" },
  { alpha2_code: "MF", countryName: "Saint Martin" },
  { alpha2_code: "PM", countryName: "Saint Pierre and Miquelon" },
  { alpha2_code: "VC", countryName: "Saint Vincent and the Grenadines" },
  { alpha2_code: "WS", countryName: "Samoa" },
  { alpha2_code: "SM", countryName: "San Marino" },
  { alpha2_code: "ST", countryName: "Sao Tome and Principe" },
  { alpha2_code: "SA", countryName: "Saudi Arabia" },
  { alpha2_code: "SN", countryName: "Senegal" },
  { alpha2_code: "CS", countryName: "Serbia and Montenegro" },
  { alpha2_code: "SC", countryName: "Seychelles" },
  { alpha2_code: "SL", countryName: "Sierra Leone" },
  { alpha2_code: "SG", countryName: "Singapore" },
  { alpha2_code: "SX", countryName: "Sint Maarten" },
  { alpha2_code: "SK", countryName: "Slovakia" },
  { alpha2_code: "SI", countryName: "Slovenia" },
  { alpha2_code: "SB", countryName: "Solomon Islands" },
  { alpha2_code: "SO", countryName: "Somalia" },
  { alpha2_code: "ZA", countryName: "South Africa" },
  { alpha2_code: "GS", countryName: "South Georgia & The South Sandwich Islands" },
  { alpha2_code: "SS", countryName: "South Sudan" },
  { alpha2_code: "ES", countryName: "Spain" },
  { alpha2_code: "LK", countryName: "Sri Lanka" },
  { alpha2_code: "SD", countryName: "Sudan" },
  { alpha2_code: "SR", countryName: "Suriname" },
  { alpha2_code: "SJ", countryName: "Svalbard and Jan Mayen" },
  { alpha2_code: "SZ", countryName: "Swaziland" },
  { alpha2_code: "SE", countryName: "Sweden" },
  { alpha2_code: "CH", countryName: "Switzerland" },
  { alpha2_code: "SY", countryName: "Syrian Arab Republic" },
  { alpha2_code: "TW", countryName: "Taiwan, Province of China" },
  { alpha2_code: "TJ", countryName: "Tajikistan" },
  { alpha2_code: "TZ", countryName: "Tanzania, United Republic of" },
  { alpha2_code: "TH", countryName: "Thailand" },
  { alpha2_code: "TL", countryName: "Timor-Leste" },
  { alpha2_code: "TG", countryName: "Togo" },
  { alpha2_code: "TK", countryName: "Tokelau" },
  { alpha2_code: "TO", countryName: "Tonga" },
  { alpha2_code: "TT", countryName: "Trinidad and Tobago" },
  { alpha2_code: "TN", countryName: "Tunisia" },
  { alpha2_code: "TR", countryName: "Turkey" },
  { alpha2_code: "XT", countryName: "Turkish Rep N Cyprus (temporary code)" },
  { alpha2_code: "TM", countryName: "Turkmenistan" },
  { alpha2_code: "TC", countryName: "Turks and Caicos Islands" },
  { alpha2_code: "TV", countryName: "Tuvalu" },
  { alpha2_code: "UG", countryName: "Uganda" },
  { alpha2_code: "UA", countryName: "Ukraine" },
  { alpha2_code: "AE", countryName: "United Arab Emirates" },
  { alpha2_code: "GB", countryName: "United Kingdom" },
  { alpha2_code: "US", countryName: "United States" },
  { alpha2_code: "UM", countryName: "United States Minor Outlying Islands" },
  { alpha2_code: "UY", countryName: "Uruguay" },
  { alpha2_code: "UZ", countryName: "Uzbekistan" },
  { alpha2_code: "VU", countryName: "Vanuatu" },
  { alpha2_code: "VE", countryName: "Venezuela" },
  { alpha2_code: "VN", countryName: "Vietnam" },
  { alpha2_code: "VG", countryName: "Virgin Islands, British" },
  { alpha2_code: "VI", countryName: "Virgin Islands, U.S." },
  { alpha2_code: "WF", countryName: "Wallis and Futuna" },
  { alpha2_code: "EH", countryName: "Western Sahara" },
  { alpha2_code: "YE", countryName: "Yemen" },
  { alpha2_code: "ZM", countryName: "Zambia" },
  { alpha2_code: "ZW", countryName: "Zimbabwe" }
]